name: test
on: [push, pull_request]

jobs:
  linux-all:
    strategy:
      fail-fast: false
      matrix:
        swiftver:
          - swift:5.2
          - swift:5.3
          - swift:5.4
          - swift:5.5
          - swiftlang/swift:nightly-main
        swiftos:
          - focal
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out package
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery

  macos-all:
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest-stable
          - latest
        include:
          - xcode: latest-stable
    runs-on: macos-11
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          swift test --enable-test-discovery \
            -Xlinker -rpath \
            -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx